### ISSUE TITLE
Mistake found in documentation for "generators/handler"

### ISSUE THREAD

**Issue by matthewdunsdon** [azr/generators#2]
📜  When reading the documentation, both in the README.md file or in the godoc, for the `github.com/azr/generators/handler` package, it there appear to be a mistake:

> ...
> pkg existence will be checked. The pkg needs to have funcs :
>
>     func NewDecoder(r io.Reader) *Decoder
>     func NewEncoder(r io.Reader) *Encoder
>
> and types
> ...

🤔  I was expecting to see:

> ...
>     func NewDecoder(r io.Reader) *Decoder
>      __func NewEncoder(w io.Writer) *Encoder__
> ...

🌟 If you agree that the documentation needs to be corrected, I can set up a PR to fix this, if that would be helpful.

**Comment by azr** [comment]
Hi there, correct :) I'd appreciate a PR !

**Comment by matthewdunsdon** [comment]
Created PR <https://github.com/azr/generators/pull/3> 😄
